os: osx
osx_image: xcode13.2
language: swift
script: xcodebuild clean build test -project DemoFeature/DemoFeature.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.2" ONLY_ACTIVE_ARCH=YES